server.conf:tcp_net_server.c tcp_net_socket.c
	gcc -o server.conf tcp_net_server.c tcp_net_socket.c -lpthread

client:tcp_net_client.c tcp_net_socket.c
	gcc -o client tcp_net_socket.c tcp_net_client.c -lpthread
